# Generated by Django 5.2 on 2025-04-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faultless", "0002_document_alter_rules_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="path",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
