# Generated by Django 5.1.7 on 2025-04-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faultless', '0003_document_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('review_output', models.TextField()),
            ],
        ),
    ]
