# Generated by Django 5.2.1 on 2025-05-25 08:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faultless', '0004_trace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trace',
            name='path',
        ),
        migrations.AddField(
            model_name='trace',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trace',
            name='record_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rules',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trace',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trace',
            name='review_output',
            field=models.JSONField(blank=True, default={'matches': []}),
        ),
    ]
