# Generated by Django 5.2.1 on 2025-05-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faultless', '0005_remove_trace_path_trace_file_name_trace_record_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='output_format',
            field=models.JSONField(default={'matches': [{'error_type': 'error name(only use the name i gave you)', 'message': 'simple description of the error and how to correct it', 'occurrence_index': 'occurrence times of the error', 'original': 'the error word or phrase or sentence(depend on different type of error)'}]}),
        ),
    ]
