# Generated by Django 5.2.1 on 2025-05-26 13:56

import faultless.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faultless', '0006_rules_output_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='output_format',
            field=models.JSONField(default=faultless.models.Rules.default_output_format),
        ),
    ]
